### PR TITLE
Fixing Turtle examples

### PR DESCRIPTION
**Pull request by elf-pavlik**
I fixed examples 1 & 3 and would like to get some feedback before moving on with it, so no need to merge it until i fix all the other turtle examples!
you can run
```shell
npm test
```
rel #65

### CODE REVIEW

**Comment by elf-pavlik** [comment]
@jasnell i need remove from all examples use of RDF lists in turtle
https://github.com/elf-pavlik/w3c-socialwg-activitystreams/commit/5bb7a300ea3821b9a6aca56850c5218267fa58fb#diff-67bcb8f7a6dfcefb5456db20c189cb5dL1684

**Comment by elf-pavlik** [comment]
last two examles blocked by #71 and https://github.com/zazukoians/rdf-ext/issues/17

**Comment by elf-pavlik** [comment]
after super fast updates to jsonld.js and rdf-ext by their authors, now we have working tests to prove all 24 Turtle examples matching exactly their JSON-LD equivalents :dancers: 
@jasnell please let me know if you would prefer all those commits squashed into a single one!

**Comment by jasnell** [comment]
I'd appreciate if you could squash them down, would make it easier to review. Thank you!

**Comment by elf-pavlik** [comment]
@jasnell maybe you can just cherry-pick it from https://github.com/elf-pavlik/w3c-socialwg-activitystreams/commit/141059abe7eae6830c5270992f02516c4e43d928

**Comment by elf-pavlik** [comment]
I can also make a new pull request if you find it easier this way...

**Comment by elf-pavlik** [comment]
squashed commits from this branch also available in PR with fixes for RDFa examples #75

**Comment by jasnell** [comment]
@elf .. thank you. I'll look at getting these merged in next week.

**Pull request merged**
