### PR TITLE
Restore Microformats Examples

### PR DESCRIPTION
**Pull request by dissolve**
Undoes removal of all microformats examples while keeping all the work done since their removal

### CODE REVIEW

**Comment by tantek** [comment]
+1 to publish with this change. Also, if this pull request is accepted quickly, I and I think others (@rhiaro?) may be able to take a couple of days to fix more examples.

**Comment by jasnell** [comment]
On the call, we resolved to give it two weeks additional review. As I am on vacation for the remainder of this week and all next week, I won't be reviewing this change or merging it until at least June 23rd.

**Comment by jasnell** [comment]
@dissolve ... quick review shows that this change looks ok but I'm going to hold off merging until after it's discussed more on the call on Tuesday. Overall, I'm still leaning more towards simply removing the RDFa and Microdata examples as well as the Microformats examples from the main spec and moving those into a non-normative Note. It would be far easier to maintain and iterate overall, and would allow us to go into more detail on the substantive differences between the various options.

**Comment by jasnell** [comment]
Landed in https://github.com/jasnell/w3c-socialwg-activitystreams/commit/307cb234edc982db6adbd22bc609680793fee182

**Pull request closed without merging**
