### PR TITLE
Fixing RDFa examples

### PR DESCRIPTION
**Pull request by elf-pavlik**
similar to #70

PR for discussions and tracking work, I'll squash it into less commits before merging!

rel #65

### CODE REVIEW

**Comment by jasnell** [comment]
@elf .. thank you. I'll look at getting these merged in next week.

**Comment by elf-pavlik** [comment]
@jasnell you can already cherry-pick turtle examples, for RDFa we still need to correct them. we can discuss details in this issue as we go...

BTW could you please you change your @ mention to @elf-pavlik? [at]elf subscribed someone else to this issue...

**Comment by jasnell** [comment]
Is this ready to merge?

**Comment by elf-pavlik** [comment]
nope! i created it to keep track on progress and discuss possibly not obvious changes to RDFa examples...

also since you merged not squashed #70 it has conflicts now, once we have all RDFa examples passing i will squash commits here and create new pull request or give you commit reference to cherry-pick

**Comment by jasnell** [comment]
Elf... can you take a moment to rebase and update the PR as it seems to have fallen out of sync.

**Pull request closed without merging**
