### PR TITLE
denamespace vcard

### PR DESCRIPTION
**Pull request by jasnell**

### CODE REVIEW

**Comment by dret** [comment]
just curious: this means that it's less and less possible to actually treat AS2 as JSON-LD if you do not specifically know it's AS2 and thus perform all the implicit processing that AS2 defines, but that is not made explicit in the representation, right?

**Comment by jasnell** [comment]
How so?

**Comment by dret** [comment]
my assumption was that with the vcard namespace being explicit, generic JSON-LD processors will understand that the referenced concepts are actually the vcard ones. by folding them into the AS2 namespace, that visibility is lost. if that's not what's happening and generic JSON-LD clients still can identify vcard properties, then all is great!

**Comment by jasnell** [comment]
Specifically, if you get AS2 but don't know it's AS2, then you would fallback either on JSON-LD APIs or heuristic checks. For instance, suppose you get:

```json
{
  "@context": "http://example.org/foo",
  "@type": "Person",
  "given-name": "Joe",
  "displayName": "Joe Smith"
}
```
And the media type is just `application/json+ld`. You don't know for certain that this is Activity Streams but you can tell that it's JSON-LD. You have two options:

1. See if you can process it as regular JSON and get the right information (if it walks like a duck....). 

2. See if you can use JSON-LD expansion and get the right information (after expansion is there an `http://www.w3.org/ns/activitystreams#displayName` property, for instance).

In either case, you may not know it's AS2 in advance but you can find out if it *looks* like AS2 rather easily and handle it accordingly. As a best practice tho, publishers should be making use of the `application/activity+json` media type to make it clear.

The Vcard terms are not being folded into the Activity Streams namespace. In the JSON-LD context document, terms like "fn" are being mapped to "vcard:fn", so any JSON-LD processor will be able to expand those appropriately.

**Comment by dret** [comment]
thanks for clarifying this, so it's basically just a local rename. very good.

**Pull request merged**
