### PR TITLE
Drop Relationship and subject

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Implements issue #289.

- Drops the "Relationship" class and "relationship" property from vocabulary
- Drops the related "subject" property
- Simplifies `Modeling "friend requests"` section

### CODE REVIEW

**Comment by jasnell** [comment]
I'm -1 on this. There are definite use cases for this.

**Comment by dmitrizagidulin** [comment]
Can you give an example?

**Comment by dmitrizagidulin** [comment]
@jasnell - might Relationships not be better implemented as an extension, rather than in the core AS2 vocabulary?

**Comment by elf-pavlik** [comment]
Instead of defining Qualified Relation on vocabulary level API could handle such requirements for example with http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/
```
{
"@context": "http://www.w3.org/ns/activitystreams",
"type": "Relationship",
"subject": {
  "type": "Person",
  "name": "Sally"
},
"relationship": "http://purl.org/vocab/relationship/closeFriendOf",
"object": {
  "type": "Person",   
  "name": "John"
}
```
could become result of

http://example.org/dataset?subject={Sally}&predicate={http://purl.org/vocab/relationship/closeFriendOf}&object={John}

of course both JSON-LD example and my TPF query should use URIs instead of Sally and John

**Comment by evanp** [comment]
So, we're not going to do this after all. See #289

**Pull request closed without merging**
