### PR TITLE
more updates for microformats examples

### PR DESCRIPTION
**Pull request by dissolve**

### CODE REVIEW

**Comment by jasnell** [comment]
@dissolve ... would you be able to do a quick rebase on this one?

**Comment by dissolve** [comment]
@jasnell sure, i was afraid of that issue, there will be more once issue #80 PR is pulled in, so I'll wait until after that then fix this PR

**Comment by jasnell** [comment]
@dissolve ... Ok, I've merged the #80 PR.

**Comment by dissolve** [comment]
@jasnell rebase complete, can be automatically merged

**Pull request merged**
