### PR TITLE
Fixmicroformats

### PR DESCRIPTION
**Pull request by dissolve**
Fixes a good number of microformats examples to current best practices.

### CODE REVIEW

**Comment by jasnell** [comment]
@dissolve .. Are you ready for this to be merged?

**Comment by dissolve** [comment]
@jasnell while it doesn't correct ALL microformats examples, it at least gets most of them to current best practices and I feel its at a good point to have others look at it before I continue much further.

**Comment by jasnell** [comment]
Ok. Can you please take a moment to squash the commits?

**Comment by dissolve** [comment]
redone as PR https://github.com/jasnell/w3c-socialwg-activitystreams/pull/140

**Pull request closed without merging**
