### PR TITLE
various cleanups

### LINKED ISSUE #206: Object parameter "@id": Mandatory or not?
What I noticed when digging into the specification of AS2:

"Object" is the "base" class for most other AS classes. It is even explicitly stated, that e.g. "Activity" extends "Object". Yet even though "Object" has a mandatory parameter "@id" (being an IRI), this "@id" never shows up in any examples or specifications of subclasses such as "Activity".

http://www.w3.org/TR/activitystreams-core/, Section 3.1 states that 
> In addition to having a global identifier (expressed as an absolute IRI using the JSON-LD @id keyword) and an "object type" (expressed using the JSON-LD @type keyword), all instances of the Object class share a common set of properties normatively defined by the Activity Vocabulary.

Is "@id" actually a mandatory thing? I think either it should be marked as optional or added to the examples.

### PR DESCRIPTION
**Pull request by jasnell**
* map `@id` and `@type` to `id` and `type` (per #232)
* shift some sections around to improve structure
* clarify that language map keys must be well-formed as opposed to the stricter RFC5646 "valid" requirements (per: http://www.w3.org/TR/2015/WD-international-specs-20151020/#lang_values_valid)
* clarify that relative IRI/URI references should not be used.
* clarify requirements around CURIE support (/cc @elf-pavlik )
* mention use of the special `und` language tag in maps (`und` is a registered ISO language code)
* simplify natural language values by removing the json-ld value object option (per #222)
* remove extraneous examples (spec simplification)
* remove the section on aggregating extensions (spec simplification, not critical to basic function)
* remove the section dealing with AS 1.0 compatibility (ship has largely sailed)
* remove the AS 1.0 properties from the vocabulary
* other various editorial updates
* clarifies that `@id` is not required (Fixes #206)

### CODE REVIEW

**Comment by elf-pavlik** [comment]
> clarify requirements around CURIE support (/cc @elf-pavlik )

Thank you James! Now I consider #207 properly addressed

**Comment by jasnell** [comment]
@annando ... included the edit to natural language values discussed in https://github.com/jasnell/w3c-socialwg-activitystreams/issues/222

**Comment by annando** [comment]
@jasnell Thanks! I've got some additional questions:

* Can properties like "content" and "contentMap" be used in the same document? Or can only *exactly* one be used?
* If both can exist in the same document then the question is which one has the priority?
* Could one define a "content" (with the default language set to "de") and an additional "contentMap" with the alternate languages "en", "fr" and "es"?

**Comment by jasnell** [comment]
@annando ... yes, `content` and `contentMap` can both be used. Neither takes precedence over the other. For instance:

```json
{
  "@context": "http://www.w3.org/ns/activitystreams#",
  "@type": "Note",
  "content": "Bar",
  "contentMap": {
    "en": "Foo",
    "es": "Baz"
  }
}
```

In this example, the `Note` object has three alternative content values:

* `Bar` - no language tag
* `Foo` - `en`
* `Baz` - `es`

None of these takes precedence over the over. A consumer would simply pick the one that works best for their own locale. 

It changes only slightly if a default language context is established:

```json
{
  "@context": [
    "http://www.w3.org/ns/activitystreams#", 
    {"@language": "en"}
  ],
  "@type": "Note",
  "content": "Bar",
  "contentMap": {
    "en": "Foo",
    "es": "Baz"
  }
}
```

* `Bar` - `en`
* `Foo` - `en`
* `Baz` - `es`

In this case, the publisher is just doing something silly and ambiguous (defining two `en` tagged values). The consumer just picks one and moves on.

**Comment by annando** [comment]
Concerning the last example: Wouldn't it be better to strictly forbid publishing different content in the same language?

Something like: "You MAY use both "content" and "contentMap" but you MUST NOT define content in the same language"?

You know that it is silly, I know that it is silly. But I bet that someone eventually **will** do it.

**Comment by jasnell** [comment]
While it is silly, it's not necessarily beneficial to be overly restrictive. Sure it's likely to happen but it would typically be a bug in the implementation that would get fixed easily if it's a challenge. (that is, it's one of the obvious kinds of "hey, don't do that" type of things).

**Comment by jasnell** [comment]
Pushed a few additional edits.

**Comment by jasnell** [comment]
WG approved accepting this.

**Comment by jasnell** [comment]
Landed

**Pull request closed without merging**
