### PR TITLE
made activitystreams2.owl pass turtle-validator

### PR DESCRIPTION
**Pull request by elf-pavlik**
noticed in #65 
validated with https://github.com/mmlab/TurtleValidator

### CODE REVIEW

**Comment by elf-pavlik** [comment]
@jasnell do you see any problem with merging this one? i share links to this file which according to validator currently has invalid turtle :disappointed: 

you may also like to check out this small nuance in turtle https://github.com/RubenVerborgh/N3.js/issues/30#issuecomment-63392906

**Comment by elf-pavlik** [comment]
@RubenVerborgh would you say with confidence that we can rely on this turtle-validator?
I mostly would like to double check that blank nodes shouldn't use **.** before closing square bracket. Most errors came from that so also most of my edits just remove this **.**

**Comment by RubenVerborgh** [comment]
I actually didn't know about this validator, even though it's written by the guy next to me :smile:

That said, yes you can rely on this, as N3.js passes all Turtle spec tests and is battle-tested.
I [upgraded](https://github.com/mmlab/TurtleValidator/commit/e982b39182d669ad7179fd77ca7b52b54050e1bb) to the latest N3.js version, which includes several bugfixes.

**Comment by RubenVerborgh** [comment]
And [here](https://github.com/RubenVerborgh/N3.js/commit/5a8f215cf5b65268be355aeb641fd82f6e2d2d67)'s a patch to N3.js in case your blank nodes are really broken (using a `.` inside of them _and_ omitting a closing bracket `]`).

**Pull request merged**
